---
title: "Boxplots for genotype-based genetic interaction exploration"
author:
- name: "Martin Brand"
- name: "Kathi Zarnack"
date: "2023-01-02 - 2023-06-29"
abstract: "As an extension to the workflow, we visualize the dependency scores directly for a selected gene. Below we show the dependency scores for WRN for microsatellite instable and microsatellite instable cell lines as a reference."
output:
  bookdown::html_document2:
    code_folding: hide
    fig_caption: yes
    number_sections: no
    theme: cerulean
    toc: yes
    toc_depth: 3
    toc_float: yes
    toc_collapsed: yes
    fig_width: 8 
    fig_height: 4 
  bookdown::pdf_document2:
    keep_tex: yes
    fig_caption: yes
    number_sections: no
    toc: yes
    toc_depth: 3
graphics: yes
header-includes:
- \makeatletter\renewcommand*{\fps@figure}{h}\makeatother
- \usepackage{placeins}
geometry: margin=1in
fontsize: 18pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, message=FALSE}
library(ggplot2)
library(gridExtra)
library(ggpubr)
library(readxl)
library(kableExtra)
```

# Classification settings and target gene
```{r}
genotype <- "TP53"
target.gene <- "MDM2"
```

# Data preprocessing
```{r, warning=FALSE}
# specify the path to the processed gene-screening datasets, CCLE mutation
# dataset, file with DepMap and CCLE IDs, and MSI status dataset
data.dir <-
  "C:/Users/Martin/Documents/Master/Thesis/genetic_dependency_detection/data/"
cancer.names <- readRDS(paste0(data.dir, "cancer.names.rds"))
CCLE.mut <- readRDS(paste0(data.dir, "CCLE.mut.rds"))
dep.scores.DRIVE <- readRDS(paste0(data.dir, "dep.scores.DRIVE.rds"))
dep.scores.Achilles <- readRDS(paste0(data.dir, "dep.scores.Achilles.rds"))

class.table.MSI <- read_excel(paste0(data.dir, "supplementary_table.xlsx"))

# keep only important columns
class.table.MSI <- class.table.MSI[,c(1,4)]

# remove NAs
class.table.MSI[class.table.MSI=="NA"] <- NA
class.table.MSI <- na.omit(class.table.MSI)

# remove rows which are classified as intermediate
class.table.MSI <- class.table.MSI[class.table.MSI$CCLE_MSI!="indeterminate",]

source("helper_functions/create.classification.table.mut.vs.non.mut.R")
source("helper_functions/calc.mean.diffs.and.p.values.R")
source("helper_functions/create_barcharts_classifications.R")
source("helper_functions/create.dep.score.boxplots.R")
source("helper_functions/create.dep.score.boxplots.MSI.R")
```

# Classification
```{r}
class.table <- create.classification.table.mut.vs.non.mut(
  CCLE_mut = CCLE.mut,
  cancer_names = cancer.names,
  gene_ID = genotype, 
  DRIVE = dep.scores.DRIVE,
  Achilles = dep.scores.Achilles)

colnames(class.table$Achilles)[2] <- "isMutated"
colnames(class.table$DRIVE)[2] <- "isMutated"

# show one table for illustration
class.table$DRIVE %>%
  head() %>%
  kbl() %>%
  kable_styling()
```

# Do the distributions of both samples differ?
```{r}
boxplot.target.gene.Achilles <- 
  create.dep.score.boxplots(
    dep.scores = dep.scores.Achilles,
    target.gene = target.gene,
    genotype = genotype,
    class.table = class.table$Achilles,
    dataset = "Achilles",
    show.y.label = F)

boxplot.target.gene.DRIVE <- 
  create.dep.score.boxplots(
    dep.scores = dep.scores.DRIVE,
    target.gene=target.gene,
    genotype = genotype,
    class.table = class.table$DRIVE,
    dataset = "DRIVE")

grid.arrange(boxplot.target.gene.DRIVE, boxplot.target.gene.Achilles, ncol = 2)
```

# Comparison to MSI/MSS against WRN
```{r}
boxplot.target.gene.Achilles.MSI <- create.dep.score.boxplots.MSI(
  dep.scores = dep.scores.Achilles,
  target.gene = "WRN",
  class.table = class.table.MSI,
  dataset = "Achilles",
  show.y.label = F)

boxplot.target.gene.DRIVE.MSI <- create.dep.score.boxplots.MSI(
  dep.scores = dep.scores.DRIVE,
  target.gene = "WRN",
  class.table = class.table.MSI,
  dataset = "DRIVE")

grid.arrange(boxplot.target.gene.DRIVE.MSI, boxplot.target.gene.Achilles.MSI,
             ncol = 2)
```
Here are the package versions for successful reproduction.
```{r, session_info, include=T, echo=T, results='markup'}
sessionInfo()
```
