---
title: "Boxplots for expression-based genetic interaction exploration"
author:
- name: "Martin Brand"
- name: "Kathi Zarnack"
date: "2023-01-02 - 2023-06-29"
abstract: "As an extension to the workflow, we visualize the dependency scores directly for a selected gene."
output:
  bookdown::html_document2:
    code_folding: hide
    fig_caption: yes
    number_sections: no
    theme: cerulean
    toc: yes
    toc_depth: 3
    toc_float: yes
    toc_collapsed: yes
    fig_width: 8 
    fig_height: 4 
  bookdown::pdf_document2:
    keep_tex: yes
    fig_caption: yes
    number_sections: no
    toc: yes
    toc_depth: 3
graphics: yes
header-includes:
- \makeatletter\renewcommand*{\fps@figure}{h}\makeatother
- \usepackage{placeins}
geometry: margin=1in
fontsize: 18pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, message=FALSE}
library(ggplot2)
library(gridExtra)
library(ggpubr)
library(readxl)
library(kableExtra)
library(dplyr)
```

# Classification settings and target gene
```{r}
# select the gene on which to base the classification
# you must specify the gene name and its Entrez ID
classification.gene.HUGO <- "FUBP1"
classification.gene.entrez <- "8880"

# select the sample portion of the cell lines
# e.g. 0.2 means that 20% with highest expression are tested
# against 20% with lowest expression
sample.share <- 0.2

# select the gene for which you want the dependency values to be displayed
target.gene <- "SF3A1"
```

# Data preprocessing
```{r, warning=FALSE}
# specify the path to the processed gene-screening datasets
path <-
  "C:/Users/Martin/Documents/Master/Thesis/genetic_dependency_detection/data/"

# load processed gene-screening datasets
dep.scores.DRIVE <- readRDS(paste0(path, "dep.scores.DRIVE.rds"))
dep.scores.Achilles <- readRDS(paste0(path, "dep.scores.Achilles.rds"))

# specify the path to the processed CCLE expression dataset
path <- "C:/Users/Martin/Documents/Master/Thesis/CCLE_data/"

# load processed CCLE expression dataset
expression.data <- readRDS(paste0(path, "Expression_Files/expression.data.rds"))

# change rownames format
rownames(expression.data) <- 
  substr(rownames(expression.data), 1, nchar(rownames(expression.data)) - 3)

# make rownames to first column
expression.data$entrez.gene.id <- rownames(expression.data)
expression.data <- expression.data %>% select(entrez.gene.id, everything())
rownames(expression.data) <- NULL

source("helper_functions/create.classification.table.expr.R")
source("helper_functions/create.dep.score.boxplots.R")

rm(path)
```

```{r}
expression.class.gene <- 
  t(expression.data[
    expression.data$entrez.gene.id == classification.gene.entrez, -1])
expression.class.gene <- as.data.frame(expression.class.gene)
expression.class.gene$CCLE_ID <- rownames(expression.class.gene)
rownames(expression.class.gene) <- NULL
colnames(expression.class.gene) <- c("expr.level", "CCLE_ID")
```

# Classification
```{r}
class.tables <- create.classification.table.expr(
  sample.share ,expression.class.gene, dep.scores.DRIVE,dep.scores.Achilles)

class.table.DRIVE <- class.tables$DRIVE
colnames(class.table.DRIVE)[2] <- "isMutated"
class.table.Achilles <- class.tables$Achilles
colnames(class.table.Achilles)[2] <- "isMutated"

rm(sample.share, expression.class.gene, class.tables)

# show one table for illustration
class.table.DRIVE %>%
  head() %>%
  kbl(caption = "Classification Table in DRIVE",
      col.names = c("CCLE_ID","isHighlyExpressing")) %>%
  kable_styling()
```


# Do the distributions of both sampes differ?
```{r}
boxplot.target.gene.Achilles <- 
  create.dep.score.boxplots(dep.scores = dep.scores.Achilles,
                            target.gene = target.gene,
                            genotype = classification.gene.HUGO,
                            class.table = class.table.Achilles,
                            dataset = "Achilles",
                            pos.p.value = 0.7,
                            sample.name.1 = "-\nlowly-expressing",
                            sample.name.2 = "-\nhighly-expressing",
                            show.y.label = F)

boxplot.target.gene.DRIVE <- 
  create.dep.score.boxplots(dep.scores = dep.scores.DRIVE,
                            target.gene = target.gene,
                            genotype = classification.gene.HUGO,
                            class.table = class.table.DRIVE,
                            dataset = "DRIVE",
                            pos.p.value = 0.7,
                            sample.name.1 = "-\nlowly-expressing",
                            sample.name.2 = "-\nhighly-expressing")

plot <- grid.arrange(boxplot.target.gene.DRIVE, boxplot.target.gene.Achilles,
                     ncol=2)
```

Here are the package versions for successful reproduction.
```{r, session_info, include=T, echo=T, results='markup'}
sessionInfo()
```